import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  body: {
    marginTop: 50,
    width: '90%',
    marginLeft: '5%',
  },
  foodInfo: {
    width: '50%',
    textAlign: 'center',
    marginLeft: '25%',
    marginRight: '25%',
  },
  title: {
    fontFamily: 'Kalam',
    fontSize: 35,
    marginBottom: 0,
    padding: 0,
    textAlign: 'center',
  },
  date: {
    fontFamily: 'Kalam',
    fontSize: 15,
    marginTop: 0,
    marginBottom: 5,
    textAlign: 'center',
  },
  deleteButton: {
    padding: 2,
    borderColor: 'black',
    borderRadius: 5,
    borderWidth: 1,
    backgroundColor: '#FFBABE',
    width: '70%',
    marginLeft: '15%',
    marginRight: '15%',
    marginBottom: 10,
  },
  delete: {
    textAlign: 'center',
    fontFamily: 'Kalam',
  },
  container: {
    flex: 1,
    flexDirection: 'row',
    borderColor: 'black',
    borderWidth: 1,
    marginBottom: 15,
    padding: 10,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'space-evenly',
  },
  recipesTitle: {
    fontFamily: 'Kalam',
    fontSize: 25,
  },
  text: {
    fontFamily: 'Kalam',
    fontSize: 20,
    fontWeight: 'bold',
    color: '#757575',
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  detailButton: {
    marginLeft: 5,
    borderWidth: 1,
    borderRadius: 5,
    padding: 4,
    backgroundColor: '#FFBABE',
    fontFamily: 'Kalam',
  },
});
