import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: '#B8E0D2',
  },
  title: {
    fontSize: 30,
    fontFamily: 'Kalam',
  },
  logo: {
    flex: 1,
    height: 120,
    width: 90,
    alignSelf: 'center',
    margin: 30,
  },
  input: {
    height: 48,
    borderRadius: 5,
    overflow: 'hidden',
    backgroundColor: 'white',
    marginTop: 10,
    marginBottom: 10,
    marginLeft: 30,
    marginRight: 30,
    paddingLeft: 16,
  },
  button: {
    backgroundColor: '#EAC4D5',
    marginLeft: 30,
    marginRight: 30,
    marginTop: 20,
    height: 48,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 5,
    borderWidth: 1,
    borderColor: 'black',
  },
  buttonTitle: {
    color: 'black',
    fontSize: 16,
    fontWeight: 'normal',
    fontFamily: 'Kalam',
  },
  smallButton: {
    backgroundColor: '#EAC4D5',
    height: 20,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 1,
    width: 75,
    marginLeft: 12,
    borderWidth: 1,
    borderColor: 'black',
  },
  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 35,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    marginTop: '50%',
  },
  buttonClose: {
    backgroundColor: '#EAC4D5',
    borderWidth: 1,
    borderColor: 'black',
  },
  textStyle: {
    color: 'black',
    fontFamily: 'Kalam',
    textAlign: 'center',
  },
  modalText: {
    marginBottom: 15,
    fontSize: 18,
    textAlign: 'center',
    fontFamily: 'Kalam',
  },
  input: {
    height: 48,
    borderRadius: 5,
    overflow: 'hidden',
    backgroundColor: 'white',
    marginTop: 10,
    marginBottom: 10,
    marginLeft: 30,
    marginRight: 30,
    paddingLeft: 16,
  },
  editName: {
    borderRadius: 5,
    backgroundColor: 'white',
    padding: 5,
    width: 175,
  },
  editDate: {
    borderRadius: 5,
    backgroundColor: 'white',
    padding: 5,
  },
  orderDate: {
    fontSize: 16,
    flexDirection: 'row',
  },
  orderDateText: {
    fontSize: 16,
    fontFamily: 'Kalam',
  },
  totalList: {
    flexDirection: 'column',
    width: 350,
  },
  tableHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
    marginBottom: 5,
    borderBottomColor: 'black',
    borderBottomWidth: 2,
  },
  tableRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
    marginBottom: 5,
  },
  itemColumn: {
    fontSize: 20,
    width: 150,
    flexDirection: 'column',
    fontFamily: 'Kalam',
  },
  expirationColumn: {
    fontSize: 20,
    flexDirection: 'column',
    marginRight: 90,
    fontFamily: 'Kalam',
  },
  datePickerStyle: {
    width: 200,
    marginTop: 20,
  },
  addItemButton: {
    backgroundColor: '#EAC4D5',
    borderWidth: 1,
    borderColor: 'black',
    borderRadius: 5,
    padding: 5,
    width: 100,
    marginTop: 5,
    alignItems: 'center',
    fontFamily: 'Kalam',
  },
  icon: {
    flexDirection: 'row'
  },
  trashIcon: {
    marginRight: 10,
  },
  nameText: {
    fontSize: 16,
    fontFamily: 'Kalam',
    width: 150
  },
  expirationText: {
    fontSize: 16,
    fontFamily: 'Kalam',
  },
  backButton: {
    marginTop: 60,
    backgroundColor: '#EAC4D5',
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 1,
    width: 65,
    marginLeft: 12,
    borderWidth: 1,
    borderColor: 'black',
    marginRight: 300,
  },
});
